# Generated by Django 4.2.13 on 2024-05-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=100)),
                ('subjectId', models.IntegerField()),
                ('open_date', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='enter_date',
            new_name='admission',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='studentId',
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
