# Generated by Django 4.2.13 on 2024-05-23 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybackend', '0002_subject_rename_enter_date_student_admission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='id',
        ),
        migrations.AlterField(
            model_name='subject',
            name='subjectId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
